[phases.setup]
providers = ["...", "python"]
nixPkgs = ["...", "libsndfile", "python39Packages.pysoundfile"]

[phases.build]
cmds = ["echo start build", "...", "echo done build"]

[start]
cmd = "python3 app.py"

