buildImage = 'ghcr.io/railwayapp/nixpacks:ubuntu-1671044363'

[phases.setup]
providers = ["...", "python", "python39Packages.pysoundfile"]
nixPkgs = ["..."]
aptPkgs = ["...", "libsndfile1-dev", "libsndfile1"]

[phases.build]
cmds = ["echo start build", "...", "sudo apt-get install libsndfile1-dev", "sudo apt-get install libsndfile1", "export LD_LIBRARY_PATH=/usr/local/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}", "ldconfig", "sudo ldconfig", "sudo ldconfig -p | grep libsndfile.so", "echo $LD_LIBRARY_PATH", "echo done build"]

[start]
cmd = "python3 app.py"

