# buildImage = 'ghcr.io/railwayapp/nixpacks:latest'

[phases.setup]
providers = ["...", "python"]
nixPkgs = ["...", "libsndfile1-dev"]

[phases.build]
cmds = ["echo start build", "...", "echo done build"]

[start]
cmd = "python3 app.py"

