[phases.setup]
providers = ["...", "python"]
nixPkgs = ["...", "libsndfile"] # Install the ffmpeg package from Nix

[phases.build]
cmds = ["echo start build", "...", "echo done build"]

[start]
cmd = "python3 app.py"

