[phases.setup]
providers = ["python"]
aptPkgs = ["..."]

[phases.build]
cmds = ["echo start build", "sudo apt-get update", "sudo apt-get install -y libsndfile1-dev", "sudo which libsndfile1-dev", "...", "echo done build"]

[start]
cmd = "python3 app.py"

