[phases.setup]
providers = ["python"]
aptPkgs = ["..."]

[phases.build]
cmds = ["echo start build", "apt-get update && apt-get install -y libsndfile1", "which libsndfile1", "...", "echo done build"]

[start]
cmd = "python3 app.py"

