[phases.setup]
providers = ["python"]
aptPkgs = ["..."]

[phases.build]
cmds = ["echo start build", "...", "echo done build"]


[start]
cmds = ["echo server start", "waitress-serve --port=80 --call app:create_app"]
