[phases.setup]
providers = ["...", "python"]
nixPkgs = ["...", "ffmpeg"] # Install the ffmpeg package from Nix
aptPkgs = ["...", "wget"]   # Install the wget package with apt-get

[phases.build]
cmds = ["echo start build", "...", "echo done build"]

[start]
cmd = "python3 app.py"

