[phases.setup]
providers = ["python"]
aptPkgs = ["..."]

[phases.build]
cmds = ["echo start build", "...", "echo done build"]

[start]
cmd = "waitress-serve --listen=0.0.0.0:$PORT --call app:create_app"
