buildImage = 'ghcr.io/railwayapp/nixpacks:ubuntu-1671044363'

[phases.setup]
providers = ["...", "python"]
nixPkgs = ["..."]
aptPkgs = ["...", "libsndfile1-dev"]

[phases.build]
cmds = ["echo start build", "...", "sudo apt-get install libsndfile1-dev", "echo done build"]

[start]
cmd = "python3 app.py"

